### ISSUE TITLE
Issue while installation awx11.0.0 

### ISSUE THREAD

**Issue by erashishpadhy** [fitbeard/awx-ha-cluster#2]
1. I have download awx11.0.0.
2. Unzip it 
3. git clone your repo
4.Updated the demo invertory file

[root@master1 awx-ha-cluster]# cat inventory/demo
[all:vars]

[postgres]
master1.otl.lab

[awx_instance_group_web]
master1.otl.lab node=primary
master2.otl.lab

[awx_instance_group_task]
master1.otl.lab node=primary
master2.otl.lab

[awx_instance_group_isolated_one]

[awx_instance_group_isolated_two]
[root@master1 awx-ha-cluster]#

I am getting output as 

TASK [postgres : Template Docker compose config] ***********************************************************************************
failed: [master1.otl.lab] (item={u'src': u'docker-compose.yml.j2', u'dst': u'docker-compose.yml'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dst": "docker-compose.yml", "src": "docker-compose.yml.j2"}, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ lookup('hashi_vault', 'secret=secret/test/data/lab/ansible/awx:data').pg_username }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'hashi_vault'. Error was a <class 'ansible.errors.AnsibleError'>, original message: No Vault Token specified"}

PLAY RECAP *************************************************************************************************************************
master1.otl.lab            : ok=9    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0
master2.otl.lab            : ok=6    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

**Comment by fitbeard** [comment]
The problem is that you trying to use examples from demo.yml variable file (https://github.com/fitbeard/awx-ha-cluster/blob/master/vars/demo.yml#L17) where examples are set to lookup secrets from Hashicorp Vault. Try set like this: https://github.com/fitbeard/awx-ha-cluster/blob/master/vars/demo.yml#L9 - in plain text or vaulted ansible secrets or setup Hashi Vault/ Azure KeyStorage.
