### ISSUE TITLE
Certificate problem in DEMO

### ISSUE THREAD

**Issue by ghorvath89** [fitbeard/awx-ha-cluster#22]
I looked for a post on this in the repo but unfortunately I couldn't find one. I only use the DEMO data so I didn't create the `secrets` folder either, I was just wondering how this installation works.
Everything is installed except the `awx-ee` container writes this error:

`awx-ee | Error: MainInstance.nodeID=awx not found in certificate name(s); names found=[awx-receptor-1.demo.io]; cfg section=tls_server; server cert=/etc/receptor/tls/receptor.crt`

Has anyone encountered this problem?
Thanks in advance!

**Comment by fitbeard** [comment]
You must meet two requirements:

> https://github.com/fitbeard/awx-ha-cluster#dependencies

> https://github.com/fitbeard/awx-ha-cluster/blob/master/roles/awx/defaults/main.yml#L15

**Comment by ghorvath89** [comment]
Thank you very much! Here https://github.com/fitbeard/awx-ha-cluster/blob/master/roles/awx/defaults/main.yml#L15 if I use no variables it works great, of course ONLY in DEMO.
