### ISSUE TITLE
More informations about default variables

### ISSUE THREAD

**Issue by SckyzO** [fitbeard/awx-ha-cluster#5]
Hello Firbeard.

Thanks for your work. I try to install your AWX Cluster version, but it's not so easy because we haven't lot of information about ansible defaults vars to use.
I don't understand how your installation works.

for example: We need
docker_registry: "dockerhost"
docker_registry_namespace: "docker-repo / awx"
But what is it?

After 2h, i can't run my cluster. So hard to configure :)

If I do not set variables like ssl_key or ssl_certificate I have an issue too. What is ssl_key and ssl_cert? path? my .pem ??

If you have the time to run your script on an empty environment (4 centos 7 servers) and complete your README and / or update group_vars with good variables. I have the time to work on this this week so I will try to successfully install AWX Cluster.

Regards,

**Comment by SckyzO** [comment]
Whaou, after 1 day I finally managed to install the cluster. Not easy but it's work. I create a new documentation for this. I can share it. 
But can you help me to unterstand how work "Isolated awx" and "webhook" ? 

Thanks,

**Comment by fitbeard** [comment]
Hi @SckyzO 
I will add more comments about defaults and webhooks with 15.x update. Info about isolated nodes you can found in separate readme on this repo or on Internet.

**Comment by elstoncawley** [comment]
Hi firstly thank you for building this awesome project.
I have a quick question, after putting in the required values in the vars/demo.yml and the inventory/demo files is there anything else that needs to be done? After I run the playbook, no docker containers get created.

**Comment by VNMan148** [comment]
Hi @SckyzO,
can you share your notes about installation here?
thanks.

**Comment by SckyzO** [comment]
Hello @VNMan148 
I started working on a fork with a little more documentation and easier to use than the firebeard code. 
You can find it here : https://github.com/SckyzO/awx-ha-cluster

**Comment by fitbeard** [comment]
> Hi firstly thank you for building this awesome project.
> I have a quick question, after putting in the required values in the vars/demo.yml and the inventory/demo files is there anything else that needs to be done? After I run the playbook, no docker containers get created.

Added v16 with all default variables in group_vars
