### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by VNMan148** [fitbeard/awx-ha-cluster#6]
I am coming from this https://github.com/sujiar37/AWX-HA-InstanceGroup
Is it just a case of following the upgrade section on this to upgrade my awx HA cluster?

**Comment by elstoncawley** [comment]
> I am coming from this https://github.com/sujiar37/AWX-HA-InstanceGroup
> Is it just a case of following the upgrade section on this to upgrade my awx HA cluster?

I would like to know the same :)

**Comment by Nikkurer** [comment]
I'm afraid - no. Because sujiar37's playbook means that awx using rabbitmq for messaging between awx nodes. As I know from 11 version AWX uses postgresql for this. Anyway I have reinstalled my awx to migrate from 9.2.0 to 14.

**Comment by Nikkurer** [comment]
I'm afraid - no. Because sujiar37's playbook means that AWX using rabbitmq for messaging between AWX nodes. As I know from the 11 version AWX uses PostgreSQL for this. Anyway, I have reinstalled my AWX to migrate from 9.2.0 to 14.
